variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: "/certs"
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: app
    MYSQL_PASSWORD: app
    MYSQL_DATABASE: shopware
    SW_HOST: "localhost"
    SW_BASE_PATH: ""
    WEB_DOCUMENT_ROOT: $CI_PROJECT_DIR/
    GIT_STRATEGY: clone
    SHOPWARE_ENV: swagmigrationconnectortest
    CHECKOUT_SHOPWARE_BRANCH: "5.7"
    PLUGIN_NAME: SwagMigrationConnector

stages:
    - Code Analysis
    - PHPUnit

default:
    tags:
        - t3.medium
    image: gitlab.shopware.com:5005/shopware/5/product/image/continuous:7.4
    services:
        -   name: mysql:5.7
            alias: mysql
    before_script:
        - zip -rq plugin.zip .
        - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/5/product/shopware.git shopware --depth=1 -b ${CHECKOUT_SHOPWARE_BRANCH}
        - unzip -q plugin.zip -d shopware/custom/plugins/${PLUGIN_NAME}
        - cd shopware
        - cp .env.dist .env
        - make init
        - php bin/console sw:plugin:refresh
        - php bin/console sw:plugin:list
        - php bin/console sw:plugin:install --activate ${PLUGIN_NAME}
        - php bin/console sw:cache:clear
        - /entrypoint supervisord &>/dev/null &

.prepare_installation_script_install_shopware: &prepare_installation_script_install_shopware
    - sed -e "s/%db\.user%/${MYSQL_USER}/g" -e "s/%db\.password%/${MYSQL_PASSWORD}/g" -e "s/%db\.database%/${MYSQL_DATABASE}/g" -e "s/%db\.host%/mysql/g" -e "s/%db\.port%/3306/g" < config.php.dist > config.php
    - php bin/console sw:database:setup --steps=drop,create,import,importDemodata
    - php bin/console sw:cache:clear
    - php bin/console sw:database:setup --steps=setupShop --shop-url=http://${SW_HOST}${SW_BASE_PATH}
    - php bin/console sw:snippets:to:db --include-plugins
    - php bin/console sw:theme:initialize
    - php bin/console sw:firstrunwizard:disable
    - php bin/console sw:admin:create --name="Demo" --email="demo@demo.de" --username="demo" --password="demo" --locale=de_DE -n
    - touch recovery/install/data/install.lock

PHP analyze:
    stage: Code Analysis
    script:
        - php bin/console -e production
        - cd custom/plugins/${PLUGIN_NAME}
        - >
            if [ $CI_PIPELINE_SOURCE == "schedule" ]; then
                sed -i "s|reportUnmatchedIgnoredErrors: true|reportUnmatchedIgnoredErrors: false|g" phpstan.neon
            fi
        - make fix-cs-dry
        - make phpstan

Code Coverage:
    stage: PHPUnit
    needs: [ PHP analyze ]
    script:
        - cd custom/plugins/${PLUGIN_NAME}
        - php -d pcov.enabled=1 -d pcov.directory=$CI_PROJECT_DIR
            ../../../vendor/bin/phpunit
            --configuration phpunit.xml.dist
            --log-junit build/artifacts/phpunit.junit.xml
            --colors=never
            --coverage-text=build/artifacts/phpunit-coverage-text
        - cat build/artifacts/phpunit-coverage-text | sed -e '/\\Shopware\\.*/d' -e '/\s*Methods:\s*\d*/d'
    coverage: '/^\s*Lines:\s*(\d+(?:\.\d+)?%)/'
    artifacts:
        paths:
            - shopware/custom/plugins/${PLUGIN_NAME}/build/artifacts/*
        reports:
            junit: shopware/custom/plugins/${PLUGIN_NAME}/build/artifacts/phpunit.junit.xml

.SW older versions:
    stage: PHPUnit
    needs: [ PHP analyze ]
    image: gitlab.shopware.com:5005/shopware/5/product/image/continuous:7.2
    before_script: [ ]
    script:
        - zip -rq plugin.zip .
        - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/5/product/shopware.git shopware --depth=1 -b ${CHECKOUT_SHOPWARE_BRANCH}
        - unzip -q plugin.zip -d shopware/custom/plugins/${PLUGIN_NAME}
        - cd shopware
        - composer install -q
        - *prepare_installation_script_install_shopware
        - php bin/console sw:plugin:refresh
        - php bin/console sw:plugin:list
        - php bin/console sw:plugin:install --activate ${PLUGIN_NAME}
        - php bin/console sw:cache:clear
        - /entrypoint supervisord &>/dev/null &
        - cd custom/plugins/${PLUGIN_NAME}
        - php ../../../vendor/bin/phpunit
            --configuration phpunit.xml.dist
            --colors=never
            --stderr
            -v
    services:
        -   name: mysql:5.7
            alias: mysql

SW 5.4:
    stage: PHPUnit
    extends: .SW older versions
    image: gitlab.shopware.com:5005/shopware/5/product/image/continuous:5.6
    variables:
        CHECKOUT_SHOPWARE_BRANCH: "5.4"

SW 5.5:
    stage: PHPUnit
    extends: .SW older versions
    image: gitlab.shopware.com:5005/shopware/5/product/image/continuous:5.6
    variables:
        CHECKOUT_SHOPWARE_BRANCH: "5.5"
    only:
        - master

SW 5.6:
    stage: PHPUnit
    extends: .SW older versions
    variables:
        CHECKOUT_SHOPWARE_BRANCH: "5.6"
    only:
        - master

.SW 5.7 default:
    stage: PHPUnit
    needs: [PHP analyze]
    script:
        - cd custom/plugins/${PLUGIN_NAME}
        - php ../../../vendor/bin/phpunit
            --configuration phpunit.xml.dist
            --colors=never

SW 5.7 PHP 7.4:
    extends: .SW 5.7 default
    only:
        - master

SW 5.7 PHP 8.0:
    extends: .SW 5.7 default
    image: gitlab.shopware.com:5005/shopware/5/product/image/continuous:8.0
