name: Integration

on:
  push:
    branches:
      - master
  pull_request:

env:
  DB_HOST: 127.0.0.1
  DB_PORT: 3306
  DB_USER: root
  DB_PASSWORD: root
  DB_NAME: shopware
  SW_HOST: localhost:8000
  SW_BASE_PATH: ""

jobs:
  phpunit:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: shopware
        ports:
          - 3306:3306
    strategy:
      matrix:
        SHOPWARE_VERSION: ["5.4", "5.5", "5.6", "5.7"]
        PHP_VERSION: ["5.6"]
        include:
          - SHOPWARE_VERSION: "5.4"
            PHP_VERSION: "5.6"
          - SHOPWARE_VERSION: "5.5"
            PHP_VERSION: "5.6"
          - SHOPWARE_VERSION: "5.6"
            PHP_VERSION: "7.2"
          - SHOPWARE_VERSION: "5.7"
            PHP_VERSION: "7.4"
          - SHOPWARE_VERSION: "5.7"
            PHP_VERSION: "8.0"
        exclude:
          - SHOPWARE_VERSION: "5.6"
            PHP_VERSION: "5.6"
          - SHOPWARE_VERSION: "5.7"
            PHP_VERSION: "5.6"

    steps:
      - name: Checkout SwagMigrationConnector
        uses: actions/checkout@v4
        with:
          path: custom/plugins/${{ github.event.repository.name }}
      - name: Setup SwagMigrationConnector
        uses: ./custom/plugins/SwagMigrationConnector/.github/actions/setup-shopware5
        with:
          shopware-version: ${{ matrix.SHOPWARE_VERSION }}
          php-version: ${{ matrix.PHP_VERSION }}
      - name: Run PHPUnit
        working-directory: custom/plugins/${{ github.event.repository.name }}
        run: php ${GITHUB_WORKSPACE}/vendor/bin/phpunit --configuration phpunit.xml.dist
